### PR TITLE
Fix spelling and grammar issues

### PR DESCRIPTION
**Pull request by svirvel**

### CODE REVIEW

**Comment by SA6JKK** [comment]
**HOME** - Become a member
thuesday --> Tuesday
coffe --> coffee
Usualy --> Usually
Usualy there’s always people --> Motsägelse, oftast finns det alltid folk på ETA --> Usually there are members here ...
I you can’t find your way call us at 031-20 78 60. --> If you can’t find your way, call us at 031-20 78 60.

**Comment by svirvel** [comment]
Tack! Nu är de delarna fixade @KonstigSak :). (Ligger bara inlagt att det ska ändras, så är inte ändrat publikt ännu).

**Comment by svirvel** [comment]
Du får gärna kolla på texterna på auktionssidan också. Särskilt på innehållet i delen "During the auction" och "Rules". Jag är lite osäker på vad vi ska ha med i del delen. @KonstigSak

**Comment by SA6JKK** [comment]
**During the auction, mina förslag på text**

It is possible to buy coffee, sandwiches, cooked meals etc. in our cafe.

During the auction, our components bar will open. This is a section of the auction where components, cables, and more are sold in a bazaar-style fashion.

Some items that we have received in a large quantity may be sold at the components bar.

Items during the auction will not follow a special order. Due to the large number of items, it's not possible for us to pick an item by request.

There is no entrance fee. However, there is a limited amount of seats and to ensure a seat it is possible to buy a ticket. The tickets can be bought from 09:00 on the auction day. Tickets are sold until they run out.

**Comment by SA6JKK** [comment]
RULES
Items are sold as-is, with no warranties given by ETA. If an item is tested as working this means that we have tested the basic functionality of the item and found it working. Unfortunately, we can't test everything in depth. An item marking as not working can mean that the equipment is completely broken or simply that a fuse needs replacement. We strive to keep the descriptions as accurate as possible but reserve ourselves against errors in the catalogue.

Lowest bid is 1 SEK.

Payment is made directly after bidding to the cashier.

_Följande stycke gillar jag inte riktigt men kan inte sätta fingret på vad som känns fel._
For persons expecting to buy a lot, it is possible to sign an account with a deposit of 500 SEK. All bought items will then be stored in a pallet which is picked up and paid for directly after the auction. To sign an account speak with the cashier before the auction begins.

**Comment by svirvel** [comment]
Tror att allt jag har hittat är fixat nu, så jag publicerar ändringarna.

**Pull request merged**
